Fixed vulnerabilities
exasol/db2-virtual-schema pull request #33
Opened 2024-03-11 13:23 UTC by ckunki

Fixs #32

2024-03-11 16:10 UTC, kaklakariada requested changes

2024-03-11 16:10 UTC, kaklakariada commented on .github/workflows/dependencies_update.yml
Mark as generated

2024-03-11 16:50 UTC, ckunki commented on .github/workflows/dependencies_update.yml
OK

2024-03-12 05:39 UTC, kaklakariada approved these changes

2024-03-12 07:29 UTC, merged